var datos = {
	"personas": [
		{"nombre":"Nombre 1","edad":30, "tipo1": true},
		{"nombre":"Nombre 2","edad":20, "tipo2": true},
		{"nombre":"Nombre 3","edad":10, "tipo1": true},
		{"nombre":"Nombre 4","edad":30, "tipo1": true},
		{"nombre":"Nombre 5","edad":20, "tipo2": true},
		{"nombre":"Nombre 6","edad":10, "tipo2": true},
		{"nombre":"Nombre 7","edad":30, "tipo2": true},
		{"nombre":"Nombre 8","edad":20, "tipo2": true},
		{"nombre":"Nombre 9","edad":10, "tipo2": true},
		{"nombre":"Nombre 10","edad":30, "tipo2": true},
		{"nombre":"Nombre 11","edad":20, "tipo1": true},
		{"nombre":"Nombre 12","edad":10, "tipo1": true},
		{"nombre":"Nombre 13","edad":30, "tipo2": true},
		{"nombre":"Nombre 14","edad":20, "tipo2": true},
		{"nombre":"Nombre 15","edad":10, "tipo1": true},
		{"nombre":"Nombre 16","edad":30, "tipo1": true},
		{"nombre":"Nombre 17","edad":20, "tipo2": true},
		{"nombre":"Nombre 18","edad":10, "tipo2": true},
		{"nombre":"Nombre 19","edad":30, "tipo1": true},
		{"nombre":"Nombre 20","edad":20, "tipo1": true},
		{"nombre":"Nombre 21","edad":10, "tipo2": true},
		{"nombre":"Nombre 22","edad":30, "tipo2": true},
		{"nombre":"Nombre 23","edad":20, "tipo2": true},
		{"nombre":"Nombre 24","edad":10, "tipo2": true},
		{"nombre":"Nombre 25","edad":30, "tipo2": true},
		{"nombre":"Nombre 26","edad":20, "tipo2": true},
		{"nombre":"Nombre 28","edad":10, "tipo2": true},
		{"nombre":"Nombre 29","edad":30, "tipo1": true},
		{"nombre":"Nombre 30","edad":20, "tipo1": true},
	],
};